### ISSUE TITLE
[Bug] update flink version to 1.16.2and CDC version to 2.3.0:NoSuchMethodError

### ISSUE THREAD

**Issue by zhegemingzimeibanquan** [ververica/flink-cdc-connectors#2340]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

2.3.0

### Database and its version

mysql 8

### Minimal reproduce step

start flink-sql client
try to build a cdc database connect and table
run select * from the table

### What did you expect to see?

run cdc success

### What did you see instead?

first is a Series of ClassNotFoundException，then i put the missing jar into ./lib 
finally ,it tells:
Caused by: java.lang.NoSuchMethodError: io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration.(Lio/debezium/config/Configuration;Ljava/util/Properties;)V

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhegemingzimeibanquan** [comment]
i try to downgrade the version of flinkcdc,it works on flink 1.13.6 and cdc 2.0.2,but i need to use flink 1.16

**Comment by foxmorg** [comment]
The same issue for me:

`Caused by: java.lang.NoSuchMethodError: 'void io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration.<init>(io.debezium.config.Configuration, java.util.Properties)'
    at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.createMySqlConnection(DebeziumUtils.java:78)
    at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.createMySqlConnection(DebeziumUtils.java:71)
    at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.checkSplitOrStartNext(MySqlSplitReader.java:138)
    at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.fetch(MySqlSplitReader.java:71)
    at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58)
    at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:142)
    at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    ... 1 more`
    
Reproduces on CDC 2.3.0 and 2.4.0 versions.

As I understand, the reason because as result we have two dependencies runtime classpath :
debezium-connector-mysql-1.6.4.Final.jar (1.9.7.Final for cdc 2.4.0)
flink-connector-mysql-cdc-2.3.0.jar

with the same class io.debezium.connector.mysql.MySqlConnection$MySqlConnectionConfiguration but first one with only one constructor.

Issue exists since this changes were merged:
https://github.com/ververica/flink-cdc-connectors/pull/1217

So the question is, why was this class renamed in this commit https://github.com/ververica/flink-cdc-connectors/commit/5415bcf0f43db627cd3604697245cc07a630f808 and how fix this issue without shading class from debezium-connector-mysql dependency?

**Comment by altairbow** [comment]
两个方法：
1. 把 `debezium-connector-mysql-1.9.7.Final.jar` 改名，比如 `flink-dep-debezium-connector-mysql-1.9.7.Final.jar`，目的是让 JVM 优先找到 flink cdc 内与 debezium 同包同名的类。
2. 把 `flink-connector-mysql-cdc-2.4.1.jar` 内的 debezium 包覆盖到 debezium-connector-mysql-1.9.7.Final.jar。

第二个方法亲测有效，第一个没试。

**Comment by gulunhui** [comment]
我已经收到你的邮件啦~~~~

**Comment by a1643977841** [comment]
> 两个方法：
> 
> 1. 把 改名，比如 ，目的是让 JVM 优先找到 flink cdc 内与 debezium 同包同名的类。`debezium-connector-mysql-1.9.7.Final.jar``flink-dep-debezium-connector-mysql-1.9.7.Final.jar`
> 2. 把 内的 debezium 包覆盖到 。`flink-connector-mysql-cdc-2.4.1.jar``debezium-connector-mysql-1.9.7.Final.jar`
> 
> 第二个方法亲测有效，第一个没试。

你好可以详细说说吗

**Comment by gulunhui** [comment]
我已经收到你的邮件啦~~~~

**Comment by zhegemingzimeibanquan** [comment]
在新版本里面，cdc的jar包和cdc-sql的jar包是两个jar包，如果需要sql-client去运行cdc程序，需要在lib里面加入cdc-sql的jar包

**Comment by gulunhui** [comment]
我已经收到你的邮件啦~~~~

**Comment by w1023563646** [comment]
亲测第一种方案可行，我的 flink-connector-mysql-cdc 版本是2.3.0，里面引用的debezium-connector-mysql 版本是1.6.4.Final，在flink-->lib下的debezium-connector-mysql-1.6.4.Final.jar 改名成 flink-dep-debezium-connector-mysql-1.6.4.Final.jar后 
重启flink服务  就不报这个错误了

**Comment by gulunhui** [comment]
我已经收到你的邮件啦~~~~

**Comment by zhu520-abc** [comment]
> 两个方法：
> 
> 1. 把 `debezium-connector-mysql-1.9.7.Final.jar` 改名，比如 `flink-dep-debezium-connector-mysql-1.9.7.Final.jar`，目的是让 JVM 优先找到 flink cdc 内与 debezium 同包同名的类。
> 2. 把 `flink-connector-mysql-cdc-2.4.1.jar` 内的 debezium 包覆盖到 `debezium-connector-mysql-1.9.7.Final.jar`。
> 
> 第二个方法亲测有效，第一个没试。


> 在flink-->lib下的debezium-connector-mysql-1.6.4.Final.jar

你好，为什么我的flink-->lib下没有debezium-connector-mysql-1.6.4.Final.jar这个包？

**Comment by gulunhui** [comment]
我已经收到你的邮件啦~~~~

**Comment by w1023563646** [comment]
> > 两个方法：
> > 
> > 1. 把 `debezium-connector-mysql-1.9.7.Final.jar` 改名，比如 `flink-dep-debezium-connector-mysql-1.9.7.Final.jar`，目的是让 JVM 优先找到 flink cdc 内与 debezium 同包同名的类。
> > 2. 把 `flink-connector-mysql-cdc-2.4.1.jar` 内的 debezium 包覆盖到 `debezium-connector-mysql-1.9.7.Final.jar`。
> > 
> > 第二个方法亲测有效，第一个没试。
> 
> > 在flink-->lib下的debezium-connector-mysql-1.6.4.Final.jar
> 
> 你好，为什么我的flink-->lib下没有debezium-connector-mysql-1.6.4.Final.jar这个包？

这个包是需要从自己的maven仓库里copy到flink-->lib下的，只有这样才能在flink管控台启动任务时不报缺少包的错误

**Comment by jingwangfei** [comment]
GET

**Comment by gulunhui** [comment]
我已经收到你的邮件啦~~~~
