### ISSUE TITLE
Oracle cdc 无法获取ddl变化信息

### ISSUE THREAD

**Issue by moresun** [ververica/flink-cdc-connectors#1677]
您好
最近使用oracle cdc进行开发，版本11g；我们希望中间发生的schema变化也能获取，为此我们把includeSchemaChanges选项配置true；
在启动flink任务时，我们捕获到了ddl信息，create table内容，但起始数据同步后，我们在原表上添加了一个字段，插入一条数据，我们发现没有捕获ddl内容，即alter信息没有，但dml数据可以看到新增的数据，还请指导

**Comment by e-mhui** [comment]
需要升级flink-connector-oracle-cdc依赖的debezium版本（默认依赖的是1.5.4.Final），经过测试1.7.0.Final以上是支持感知 DDL变化

**Comment by e-mhui** [comment]
You need to upgrade the debezium version that Flink connector oracle cdc depends on (the default is 1.5.4. Final). The 1.7.0.Final version supports capture DDL changes

**Comment by moresun** [comment]
Oracle cdc supports 11g,12c,19c 
 why not for 10g and 18c

**Comment by e-mhui** [comment]
> Oracle cdc supports 11g,12c,19c
> why not for 10g and 18c

The source code is limited. You can change the source code to test whether it supports other versions.

package: `com.ververica.cdc.connectors.oracle`
class: `OracleValidator.class`
```java

    @Override
    public void validate() {
        try (Connection connection = openConnection(properties)) {
            DatabaseMetaData metaData = connection.getMetaData();
            if (metaData.getDatabaseMajorVersion() != 19
                    && metaData.getDatabaseMajorVersion() != 12
                    && metaData.getDatabaseMajorVersion() != 11) {
                throw new ValidationException(
                        String.format(
                                "Currently Flink Oracle CDC connector only supports Oracle "
                                        + "whose version is either 11, 12 or 19, but actual is %d.%d.",
                                metaData.getDatabaseMajorVersion(),
                                metaData.getDatabaseMinorVersion()));
            }
        } catch (SQLException ex) {
            throw new TableException(
                    "Unexpected error while connecting to Oracle and validating", ex);
        }
    }
```

**Comment by moresun** [comment]
java.lang.NoClassDefFoundError: Could not initialize class io.debezium.connector.oracle.OracleConnectorConfig
	at io.debezium.connector.oracle.OracleConnectorTask.getAllConfigurationFields(OracleConnectorTask.java:140)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:119)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:759)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
If debezium version is upgraded to 1.7.2.Final , some exceptions occur in Flink 1.14.6. 
How can Flink  1.14.6  work with debezium?  Java-1.8 Scala-2.12

**Comment by moresun** [comment]
mvn install -pl flink-sql-connector-oracle-cdc -am -DskipTests -Dscala.binary.version=2.12 -Dflink.version=1.14.6 -Dmaven.test.skip=true

modify debezium version 1.7.1.Final in pox.xml

**Comment by PatrickRen** [comment]
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
